pipelines:
  branches:
    master:
      - step:
          name: Build Debug
          caches:
            - gradle
          image: bitbucketpipelines/android-ci-image
          script:
            - echo "$SIGNING_JKS_FILE" | base64 -d > android-signing-keystore.jks
            - ./gradlew uploadArchives
          artifacts:
            - libstext/build/outputs/aar/**
